EMAILC-55 - Error handling EMAIL:ACCESSING_FOLDER
mulesoft/mule-email-connector pull request #205
Opened 2021-01-08 19:50 UTC by acurci-at-mulesoft

2021-01-08 19:58 UTC, nicomz requested changes

2021-01-08 19:58 UTC, nicomz commented on src/main/java/org/mule/extension/email/internal/mailbox/imap/IMAPOperations.java
> +  @Throws({EmailListingErrorTypeProvider.class})
there is no need to wrap in array mode.

2021-01-08 20:19 UTC, nicomz approved these changes

2021-01-12 15:58 UTC, acurci-at-mulesoft commented
@nicomz @emariotti3 please, be so kind, and take a look at this PR. Thanks!

2021-01-12 16:02 UTC, nicomz approved these changes

2021-01-12 16:40 UTC, merged