EMAILC-70: Exception handling. Added error and debug log
mulesoft/mule-email-connector pull request #261
Opened 2022-01-03 14:54 UTC by acurci-at-mulesoft

2022-01-03 15:30 UTC, nicomz approved these changes

2022-01-03 16:03 UTC, juldiazmule submitted a review, later dismissed

2022-01-03 17:42 UTC, nicomz requested changes

2022-01-03 17:42 UTC, nicomz commented on src/main/java/org/mule/extension/email/internal/mailbox/imap/IMAPPollingSource.java
> +  private static final Logger LOGGER = LoggerFactory.getLogger(IMAPPollingSource.class);
Static Import

2022-01-03 17:42 UTC, nicomz commented on src/test/java/org/mule/extension/email/retriever/AbstractEmailRetrieverTestCase.java
> +    Properties props = System.getProperties();
Static Import

2022-01-04 14:30 UTC, juldiazmule submitted a review, later dismissed

2022-01-04 15:22 UTC, juldiazmule approved these changes

2022-01-04 15:30 UTC, merged