W-10673821: Add move-to-folder operation
mulesoft/mule-email-connector pull request #271
Opened 2022-03-10 13:40 UTC by giss-ignacio

2022-03-10 14:24 UTC, konangc87 requested changes

2022-03-10 14:24 UTC, konangc87 commented on src/main/java/org/mule/extension/email/internal/mailbox/imap/IMAPOperations.java
> +      javax.mail.Message message = sourceMailboxFolder.getMessageByUID(emailId);
Could the sourceMailboxFolder be null? if so, a null check should be in place and throw an FolderNotFoundException on sourceFolder.

2022-03-11 18:51 UTC, nicomz requested changes

2022-03-11 18:51 UTC, nicomz commented on src/main/java/org/mule/extension/email/internal/mailbox/imap/IMAPOperations.java
> +import org.mule.extension.email.api.exception.EmailException;
Unused Import

2022-03-11 18:51 UTC, nicomz commented on src/main/java/org/mule/extension/email/internal/mailbox/imap/IMAPOperations.java
> +import javax.mail.UIDFolder;
Unused Import

2022-03-11 18:55 UTC, nicomz requested changes

2022-03-11 18:55 UTC, nicomz commented on src/test/java/org/mule/email/mtf/TestIMAPServer.java
> +    Security.setProperty("ssl.SocketFactory.provider", DummySSLSocketFactory.class.getName());
Revert to the original value on stop.

2022-03-14 11:07 UTC, konangc87 approved these changes

2022-03-14 13:51 UTC, nicomz approved these changes

2022-03-14 13:56 UTC, merged